### ISSUE TITLE
Spring Security UI issue

### ISSUE THREAD

**Issue by randyjones** [double16/grails-cookie-session#6]
I recently upgraded a Grails project to 3.3.1. My biggest issue was with the Cookie Session plugin. I started with 3.0.1 version of the plugin but I would get errors. I forked 3.0.1 and fixed the errors but I would occasionally get errors that could only be fixed by clearing the cookies. I tried your version, 4.0.0.RC1, and it seems better but I now have an issue when a new user registers and I reauthenticate, the user does not get logged in but has to enter a user name and password again. Does you project use Spring Security and have you seen this issue?

Thanks,
Randy

**Comment by double16** [comment]
I introduced a logic bug when refactoring. The issue is in SecurityContextSessionPersistenceListener when determining if the security context should be updated in the session.

**Comment by randyjones** [comment]
Is there a version that fixes the logic bug?

**Comment by double16** [comment]
Not yet, I'm working on it. Probably will be released Friday or latest on Monday.

**Comment by double16** [comment]
Released 4.0.0.RC3. Please try it and let me know if it fixes the issue.
